# Generated by Django 3.2 on 2021-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('tipo_problema', models.CharField(max_length=35)),
                ('nivel_prioridad', models.CharField(max_length=19)),
                ('ciudad', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=3)),
                ('codigo_postal', models.CharField(max_length=5, null=True)),
                ('informacion_extra', models.TextField(max_length=256, null=True)),
            ],
        ),
    ]
